src/unpackaged/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Apex Class Name for which Log is Generated</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Log Message</description>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <description>Apex Method Name for which Log is Generated</description>
        <label>Method Name</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppLogger.cls
/*************************************************************************************************************************************************
Class Name          : AppLogger
Developer           : Suban Khoja 
Purpose             : This Class implements Logging Functionality for Exception Handling.
Last Modified Date  : 23/02/2020
*************************************************************************************************************************************************/

public class AppLogger {

    /* Class Properties START */
    /* Class Properties END */

    /* Class Methods START */
    /*********************************************************************************************************************************************
    * Class Name        : AppLogger
    * Method Name       : createErrorLog
    * Description       : This method Create an record of Log Object with details about Exception
    * Arguments         : [
        String className , 
        String methodName , 
        String message , 
        Integer lineNo
    ]
    * Return Type       : void
    * Author            : Suban Khoja
    *********************************************************************************************************************************************/
    public static void createErrorLog(String className , String methodName , String message , Integer lineNo){
        Log__c log = new Log__c(
            Class_Name__c = className,
            Method_Name__c = methodName,
            Message__c = message,
            Line_Number__c = lineNo
        );
        insert new List<Log__c>{log};
    }


    /* Class Methods END */
}